language: node_js
node_js:
  - "6"
  - "7"

branches:
  only:
    - master

env:
  global:
    - "CI_BUILD_TYPE=\"test-default\""

matrix:
  # include:
  #   - node: 7
  #     env: "CI_BUILD_TYPE=\"test-saucelabs\""
  allow_failures:
    - node: 7
      env: "CI_BUILD_TYPE=\"test-saucelabs\""

script:
  - npm run $CI_BUILD_TYPE

after_success:
  - cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov
