language: node_js

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 6
      install:
        - npm install
      script:
        - npm run test-default
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 7
      install:
        - npm install
      script:
        - npm run test-default
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 7
      install:
        - npm install
        - npm install karma-sauce-launcher
      script:
        - npm run test-saucelabs
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install
        - npm install electron karma-electron-launcher
      script:
        - npm run test-electron
    - stage: test
      os: osx
      env: CI_BUILD_TYPE=electron
      node_js: 7
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install
        - npm install electron karma-electron-launcher
      script:
        - npm run test-electron
    - stage: test
      os: osx
      env: CI_BUILD_TYPE=nativescript
      node_js: 7
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - npm install
      script:
        - npm run test-nativescript-ios
    - stage: test
      os: linux
      env: CI_BUILD_TYPE=nativescript
      language: android
      jdk: oraclejdk8
      node_js: 7
      android:
        components:
          - platform-tools
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - sys-img-armeabi-v7a-android-19
      install:
        - export DISPLAY=':99.0'
        - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
        - nvm install 7
        - npm install -g nativescript
        - tns usage-reporting disable
        - tns error-reporting disable
        - npm install
      before_script:
        - echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      script:
        - npm run test-nativescript-android
    - stage: deploy
      os: linux
      env: CI_BUILD_TYPE=docs
      node_js: 7
      install:
        - npm install documentation
        - npm install
      script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "travis-ci"
        - git clone https://${GH_TOKEN}@github.com/Chialab/proteins.wiki.git wiki
        - ./node_modules/.bin/documentation build src/**/*.js -f md > ./wiki/API.md
        - cd wiki
        - git add .
        - git commit -m "Lastest api reference on successful travis build $TRAVIS_BUILD_NUMBER auto-pushed to wiki"
        - git push origin
  allow_failures:
    - env: CI_BUILD_TYPE=electron
    - env: CI_BUILD_TYPE=saucelabs
    - env: CI_BUILD_TYPE=nativescript
    - env: CI_BUILD_TYPE=docs

addons:
  apt:
    packages:
      - xvfb

after_success:
  - cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov
