language: node_js

jobs:
  include:
    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 9
      before_install:
        - yarn global add @chialab/rna-cli
      install:
        - yarn install
      script:
        - rna unit 'test/*.js' --node

    - stage: test
      env: CI_BUILD_TYPE=default
      node_js: 10
      before_install:
        - yarn global add @chialab/rna-cli
        - yarn add codecov
      install:
        - yarn install
      script:
        - rna unit 'test/*.js' --node --coverage
      after_success:
        - cat reports/unit/coverage/*/lcov.info | ./node_modules/.bin/codecov

    - stage: test
      os: linux
      env: CI_BUILD_TYPE=saucelabs
      node_js: 10
      before_install:
        - yarn global add @chialab/rna-cli
      install:
        - yarn install
      script:
        - rna unit 'test/*.js' --saucelabs --context 'test/context.html' --concurrency 1

    - stage: deploy
      os: linux
      env: CI_BUILD_TYPE=docs
      node_js: 10
      before_install:
        - yarn global add @chialab/rna-cli
      install:
        - yarn install
      before_script:
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "travis-ci"
      script:
        - git clone https://${GH_TOKEN}@github.com/Chialab/proteins.wiki.git wiki
        - rna documentate --output ./wiki/API.md
        - cd wiki
        - git add .
        - git diff-index --quiet HEAD || git commit -m "Lastest api reference on successful travis build ${TRAVIS_BUILD_NUMBER} auto-pushed to wiki"
        - git push origin

  allow_failures:
    - env: CI_BUILD_TYPE=saucelabs
    - env: CI_BUILD_TYPE=docs
