language: node_js

node_js:
  - 6
  - 7

branches:
  only:
    - master

env:
  global:
    - CI_BUILD_TYPE=default

matrix:
  include:
    - os: linux
      node_js: 7
      env: CI_BUILD_TYPE=saucelabs
    - os: linux
      node_js: 7
      env: CI_BUILD_TYPE=electron
    - os: osx
      node_js: 7
      env: CI_BUILD_TYPE=electron
    - os: osx
      node_js: 7
      env: CI_BUILD_TYPE=nativescript
    - os: linux
      language: android
      jdk: oraclejdk8
      node_js: 7
      android:
        components:
          - platform-tools
          - build-tools-23.0.1
          - android-23
          - extra-android-m2repository
          - sys-img-armeabi-v7a-android-19
      env: CI_BUILD_TYPE=nativescript
    - stage: docs
      os: linux
      node_js: 7
      env: CNAME=docs.chialab.io
      before_install:
        - pip install --user awscli
        - mkdir -p docs
        - npm install
      script:
        - npm run docs
      after_success:
        - aws s3 sync docs s3://$CNAME/~chialab/proteins/latest --region eu-west-1 --delete
        - aws cloudfront create-invalidation --paths '/~chialab/proteins/latest/*' --distribution-id $(aws cloudfront list-distributions | python -c 'import json, os, sys; print([d["Id"] for d in json.loads(sys.stdin.read()).get("DistributionList", {}).get("Items", []) if os.environ.get("CNAME") in d.get("Aliases", {}).get("Items", [])][0])')

  allow_failures:
    - env: CI_BUILD_TYPE=electron
    - env: CI_BUILD_TYPE=saucelabs
    - env: CI_BUILD_TYPE=nativescript
    - stage: docs

addons:
  apt:
    packages:
      - xvfb

install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
  - |
    if [ "$CI_BUILD_TYPE" = 'nativescript' ]; then
      nvm install 7
      npm install -g nativescript
      tns usage-reporting disable
      tns error-reporting disable
      export CI_BUILD_TYPE="$CI_BUILD_TYPE-$TRAVIS_OS_NAME"
    fi
  - npm install
  - |
    if [ "$CI_BUILD_TYPE" = 'electron' ]; then
      npm install electron karma-electron-launcher
    fi
  - |
    if [ "$CI_BUILD_TYPE" = 'saucelabs' ]; then
      npm install karma-sauce-launcher
    fi

before_script:
  - |
    if [ "$CI_BUILD_TYPE" = 'nativescript-linux' ]; then
      echo no | android create avd --force -n test -t android-19 -b armeabi-v7a
      emulator -avd test -no-audio -no-window &
      android-wait-for-emulator
    fi

script:
  - npm run test-$CI_BUILD_TYPE

after_success:
  - cat coverage/report-lcov/*/lcov.info | ./node_modules/.bin/codecov
