name: Main
on: push

jobs:
  # BUILD
  build:
    name: Build
    runs-on: ubuntu-latest
    if: contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: npm install -g @chialab/rna-cli@beta

      - run: yarn install

      - run: yarn run lint

      - run: yarn run build

      - uses: actions/cache@v2
        with:
          path: dist
          key: build-${{ github.sha }}

  # TEST
  test-node:
    name: Test Node
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: npm install -g @chialab/rna-cli@beta

      - run: yarn install

      - uses: actions/cache@v2
        with:
          path: dist
          key: build-${{ github.sha }}

      - run: yarn run test:node

      - uses: codecov/codecov-action@v1
        with:
          file: coverage/*/lcov.info

  test-browsers:
    name: Test Browsers
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: '14'

      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ~/.npm
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - run: npm install -g @chialab/rna-cli@beta

      - run: yarn install

      - uses: actions/cache@v2
        with:
          path: dist
          key: build-${{ github.sha }}

      - run: yarn run test:saucelabs
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_ACCESS_KEY: ${{ secrets.SAUCE_ACCESS_KEY }}

      - uses: codecov/codecov-action@v1
        with:
          file: coverage/*/lcov.info

  # DOCS
  api:
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_WIKI_TOKEN }}
        run: |
          git config --global user.email "dev@chialab.io"
          git config --global user.name "chialab-io"
          git clone https://${GITHUB_TOKEN}@github.com/chialab/proteins.wiki.git wiki
          cd wiki
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -B ${GITHUB_REF#refs/heads/}
          cp -rf ../docs/* .
          git add .
          git diff-index --quiet HEAD || git commit -m "Lastest api reference ${GITHUB_REF#refs/heads/} auto-pushed to wiki"
          git push --set-upstream origin ${GITHUB_REF#refs/heads/} --follow-tags
          cd ..
