name: Wiki
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
    tags-ignore:
      - '*'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  deploy:
    name: Deploy Wiki
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v1
      - name: Push documentation to wiki
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_WIKI_TOKEN }}
        run: |
          git config --global user.email "dev@chialab.io"
          git config --global user.name "chialab-io"
          git clone https://${GITHUB_TOKEN}@github.com/chialab/proteins.wiki.git wiki
          cd wiki
          git checkout ${GITHUB_REF#refs/heads/} || git checkout -B ${GITHUB_REF#refs/heads/}
          cp -rf ../docs/* .
          git add .
          git diff-index --quiet HEAD || git commit -m "Lastest api reference ${GITHUB_REF#refs/heads/} auto-pushed to wiki"
          git push --set-upstream origin ${GITHUB_REF#refs/heads/} --follow-tags
          cd ..
